##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        modules/dxp/apps/ai-hub/ai-hub-site-initializer/src/main/resources/site-initializer/documents/company/chatbot/**