#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    liferay-aihub-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#
com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

server.port=58081